### ISSUE TITLE
Unknown node type ExportDefaultDeclaration

### ISSUE THREAD

**Issue by vesparny** [jscs-dev/babel-jscs#17]
running `babel-jscs@2.0.1` and `jscs@1.13.1`

I got this error

```
Error: Unknown node type ExportDefaultDeclaration.
    at Controller.traverse (/Users/aarnodo/code/react-kickstart/node_modules/jscs/node_modules/estraverse/estraverse.js:517:31)
    at Object.traverse (/Users/aarnodo/code/react-kickstart/node_modules/jscs/node_modules/estraverse/estraverse.js:709:27)
    at Object.iterate (/Users/aarnodo/code/react-kickstart/node_modules/jscs/lib/tree-iterator.js:9:20)
    at Object.JsFile.iterate (/Users/aarnodo/code/react-kickstart/node_modules/jscs/lib/js-file.js:359:29)
    at Object.JsFile._buildNodeIndex (/Users/aarnodo/code/react-kickstart/node_modules/jscs/lib/js-file.js:752:14)
    at Object.JsFile (/Users/aarnodo/code/react-kickstart/node_modules/jscs/lib/js-file.js:39:28)
    at StringChecker._createJsFileInstance (/Users/aarnodo/code/react-kickstart/node_modules/jscs/lib/string-checker.js:202:16)
    at StringChecker.checkString (/Users/aarnodo/code/react-kickstart/node_modules/jscs/lib/string-checker.js:104:25)
    at null.<anonymous> (/Users/aarnodo/code/react-kickstart/node_modules/jscs/lib/checker.js:43:21)
    at Array.<anonymous> (/Users/aarnodo/code/react-kickstart/node_modules/jscs/node_modules/vow/lib/vow.js:711:39)
    at Immediate.callFns [as _onImmediate] (/Users/aarnodo/code/react-kickstart/node_modules/jscs/node_modules/vow/lib/vow.js:23:35)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

here the source file 

``` js
export default function () {
  console.log('hello');
};
```

**Comment by mrjoelkemp** [comment]
Thanks for reporting. Please use the latest master of jscs. That will fix
the issue.

**Comment by hzoo** [comment]
Sorry maybe it should be more clear `babel-jscs` will only work on the master branch until we release another version

``` js
// package.json
{
  "jscs": "jscs-dev/node-jscs#master",
  "jscs": "jscs-dev/node-jscs#4d70439" // commit that supports babel-jscs
  "jscs": "^2.0.0" // whenever the next release is
}
```

https://github.com/jscs-dev/babel-jscs/releases/tag/v2.0.0
