### ISSUE TITLE
Error running rule disallowSpacesInFunctionDeclaration

### ISSUE THREAD

**Issue by okonet** [jscs-dev/babel-jscs#5]
```
disallowSpacesInFunctionDeclaration: Error running rule disallowSpacesInFunctionDeclaration: This is an issue with JSCS and not your codebase.
Please file an issue (with the stack trace below) at: https://github.com/jscs-dev/node-jscs/issues/new
TypeError: Cannot read property 'range' of null
    at Object.JsFile.getFirstNodeToken (/Users/okonet/Projects/adverity/web-app/node_modules/jscs/lib/js-file.js:207:46)
    at /Users/okonet/Projects/adverity/web-app/node_modules/jscs/lib/rules/disallow-spaces-in-function-declaration.js:80:42
    at Array.forEach (native)
    at Object.JsFile.iterateNodesByType (/Users/okonet/Projects/adverity/web-app/node_modules/jscs/lib/js-file.js:426:42)
    at Object.module.exports.check (/Users/okonet/Projects/adverity/web-app/node_modules/jscs/lib/rules/disallow-spaces-in-function-declaration.js:77:14)
    at null.<anonymous> (/Users/okonet/Projects/adverity/web-app/node_modules/jscs/lib/string-checker.js:141:22)
    at Array.forEach (native)
    at StringChecker._checkJsFile (/Users/okonet/Projects/adverity/web-app/node_modules/jscs/lib/string-checker.js:137:31)
    at StringChecker.checkString (/Users/okonet/Projects/adverity/web-app/node_modules/jscs/lib/string-checker.js:117:14)
    at null.<anonymous> (/Users/okonet/Projects/adverity/web-app/node_modules/jscs/lib/checker.js:43:21)
```

**Comment by mrjoelkemp** [comment]
Thanks for reporting. Mind supplying a code sample please?

**Comment by okonet** [comment]
I've tried to reproduce it on a small example and could not. I'll check it on my codebase, but seems this one is invalid, so I'm closing it for now.
